# start image
FROM debian:buster

## installation process
#
RUN apt-get -y update \
&& apt-get -y upgrade \
\
#php
&& apt-get -y install php php-cgi php-cli php-mbstring php-fpm php-mysql \
#using wordpress
php-curl php-gd php-intl php-soap php-xml php-xmlrpc php-zip \
#wget for downloading 
wget vim

COPY ./srcs/webserv /root/
WORKDIR /root/
CMD ["/bin/bash", "./webserv"]